name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on MacOS
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      UTM_VERSION: '0.13.0'
      BOOST_VERSION: '1.84.0'
      XERCES_C_VERSION: '3.2.5'
      CIBW_BEFORE_ALL: |
        bash .github/build_boost.sh
        bash .github/build_xerces_c.sh
        bash .github/build_utm.sh
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
        DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-listdeps {wheel} &&
        DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: |
          export BOOST_BASE=$(pwd)/dist/boost
          export XERCES_C_BASE=$(pwd)/dist/xerces-c
          export UTM_BASE=$(pwd)/dist/utm
          export REPAIR_LIBRARY_PATH=${UTM_BASE}/lib:${BOOST_BASE}/lib:${XERCES_C_BASE}/lib}:${LD_LIBRARY_PATH}
          export DYLD_LIBRARY_PATH=${REPAIR_LIBRARY_PATH}
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos
          path: ./wheelhouse/*.whl
