name: Build wheels

on: [push, workflow_dispatch]

env:
  UTM_VERSION: 0.13.0
  BOOST_VERSION: 1.84.0
  XERCES_C_VERSION: 3.2.5

jobs:
  build_wheels_linux:
    name: Build wheels for Linux
    runs-on: ubuntu-latest
    env:
      CIBW_SKIP: pp*
      CIBW_ENVIRONMENT: >
        BOOST_BASE=/project/dist
        XERCES_C_BASE=/project/dist
        UTM_BASE=/project/dist
        LD_LIBRARY_PATH=/project/dist/lib
      CIBW_BEFORE_ALL: |
        python3 .github/build.py --with-boost --with-xerces-c --install-prefix=/project/dist
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.22.0
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-linux
        path: ./wheelhouse/*.whl
  build_wheels_macos:
    name: Build wheels for MacOS
    runs-on: macos-13
    env:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
      CIBW_SKIP: pp*
      CIBW_ENVIRONMENT: >
        BOOST_BASE=${GITHUB_WORKSPACE}/dist
        XERCES_C_BASE=${GITHUB_WORKSPACE}/dist
        UTM_BASE=${GITHUB_WORKSPACE}/dist
        REPAIR_LIBRARY_PATH=${GITHUB_WORKSPACE}/dist/lib
      CIBW_BEFORE_ALL: |
        brew install swig
        python .github/build.py --with-boost --with-xerces-c --install-prefix=${GITHUB_WORKSPACE}/dist
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
        DYLD_LIBRARY_PATH="${REPAIR_LIBRARY_PATH}" delocate-listdeps {wheel} &&
        DYLD_LIBRARY_PATH="${REPAIR_LIBRARY_PATH}" delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.22.0
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos
          path: ./wheelhouse/*.whl
